name: phonefixer_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.1
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_typeahead: ^4.0.0
  intl: ^0.19.0
  syncfusion_flutter_charts: ^26.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
